stages:
  - deploy
variables:
  DISPLAY: ':99.0'

cache:
  paths:
    - node_modules/
    - .vscode-test
    - .yarn-cache

.node_env: &setup_env
  before_script:
    - apt -y update
    - apt -y install libsecret-1-dev libnss3 libgtk-3-0 libxss1 libasound2 jq xvfb
    - mkdir -p .yarn-cache
    - yarn config set cache-folder $(pwd)/.yarn-cache
    # the "reliable" package manager needs a few tries...
    - yarn install || yarn install || yarn install
    # vscode doesn't start without X
    - "/usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &"

package:
  image: node:10
  stage: deploy
  <<: *setup_env
  script:
    - yarn run clean
    - yarn run package
  artifacts:
    paths:
      - open-build-service-connector-*.vsix
