language: node_js
os:
  # - osx
  - linux
dist: bionic
node_js:
  - 12
  - 13
  - 14
services:
  - docker
  - xvfb
addons:
  apt:
    packages:
      - jq
      - gcc
      - meson
      - ninja-build
      - libsecret-1-dev
      - libglib2.0-dev
      - python3

stages:
  - test
  - lint

install:
  # try hard to install the packages
  - yarn install || yarn install || yarn install
  - ./start-mini-obs.sh
script:
  - >
    for VER in "1.40.0" "1.40.1" "1.41.0" "1.41.1" "1.42.0" "1.42.1" "1.43.0" "1.43.1" "1.43.2" "1.44.0" "1.44.1" "1.44.2" "1.45.0" "1.45.1" "1.46.0" "1.46.1" "1.47.0" "1.47.1" "1.47.2" "1.47.3" "1.48.0" "1.48.1" "1.48.2" "1.49.0" "1.49.1" "1.49.2" "1.49.3" "1.50.0" "insiders"; do
      export VSCODE_VERSION=${VER}
      mkdir tmpdir
      export TMPDIR=$(realpath ./tmpdir)
      yarn run test:quiet
      rm -rf tmpdir
      mkdir tmpdir
      yarn run test:ui
      rm -rf tmpdir
    done
cache:
  apt: true
  directories:
    - "./.vscode-test"
