language: node_js
os:
  # - osx
  - linux
node_js:
  - 10
  - 12
  - 13
services:
  - docker
  - xvfb
addons:
  apt:
    packages:
      - libsecret-1-dev
      - jq

install:
  # try hard to install the packages
  - yarn install || yarn install || yarn install
script:
  - >
    for VER in "1.40.0" "1.40.1" "1.41.0" "1.41.1" "1.42.0" "1.42.1" "1.43.0" "1.43.1" "1.43.2" "1.44.0" "1.44.1" "1.44.2" "1.45.0" "1.45.1" "insiders"; do
      export VSCODE_VERSION=${VER}
      echo "Running tests for VSCode ${VER}"
      mkdir tmpdir
      TMPDIR=$(realpath ./tmpdir) yarn run coverage
    done
cache:
  apt: true
  directories:
    - "./.vscode-test"

jobs:
  include:
    - name: test mocklibsecret
      os: linux
      dist: bionic
      cache:
        yarn: false
        apt: true
      addons:
        apt:
          packages:
            - gcc
            - meson
            - ninja-build
            - libsecret-1-dev
            - libglib2.0-dev
            - python3
      install:
        - npm install keytar
      script:
        - mkdir -p mocklibsecret/build
        - pushd mocklibsecret/build
        - meson ..
        - ninja
        - cd ..
        - ./run_tests.py
        - popd
